- hosts: "{{ variable_host | default('sandbox')}}"
  become: true
  become_user: root

  vars:
    pvScanCmd: "PVS_OUT=$(sudo pvs -o pv_name --noheadings|sed -e 's:^[\ ]*::' -e 's:[1-9].$::'|sort -u)"
    scsiScanCmd: "SCSI_OUT=$(lsscsi |awk '/sd/{print $NF}'|sort)"
    compareCmd: 'comm -3 <(echo "$PVS_OUT") <(echo "$SCSI_OUT")'
 
  tasks:
    - name: "Find free disk"
      shell: "{{ pvScanCmd }}; {{ scsiScanCmd }}; {{ compareCmd }}|tr '\n\t' ' '" 
      args:
        executable: /bin/bash
      register: freeDisk

    - name: "Create PV on {{  freeDisk.stdout }}"
      shell: >
        freeDevs="{{ freeDisk.stdout }}";  
        for disk in $freeDevs; do i
          if [ ! -b  "${disk}1" ]; 
            then (echo -e "n\np\n1\n\n\nt\n8e\nw\n\n" | /sbin/fdisk $disk ); 
          fi; 
        done
      args:
        executable: /bin/bash
      when: freeDisk.stdout is defined




